#pragma once

#define A_NOP		0x1		//+		
#define A_HALT		0x2		//+ 
#define A_JMP		0x3     //+
#define A_CMP		0x4     //+
#define A_JE		0x5     //+
#define A_JNE		0x6		//+
#define A_JL		0x7		//+
#define A_JLE		0x8		//+
#define A_JG		0x9		//+
#define A_JGE		0xA		//+
#define A_RET		0xB		//+    
#define A_CALL		0xC		//+
#define A_MOV		0xD		//+
#define A_ADD		0xE		//+
#define A_SUB		0xF		//+
#define A_MUL		0x10	//+
#define A_DIV		0x12	//+
#define A_AND		0x13	//+
#define A_OR		0x14	//+
#define A_XOR		0x15	//+
#define A_NOT		0x16	//+
#define A_IN		0x17	//+
#define A_OUT		0x18	//+
#define A_PUSH		0x19	//+
#define A_POP		0x1A	//+
#define A_INC		0x1B	//+
#define A_DEC		0x1C	//+